linters:
  enable:
    - golint
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unconvert
    - goconst
    - goimports
    - misspell
    - unparam

run:
  tests: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - golint

linters-settings:
  goconst:
    min-len: 3
    min-occurrences: 3

output:
  print-issued-lines: true
  print-linter-name: true